import'./styles.css';import{PixiRenderer}from'./render/PixiRenderer';import{ThreeRenderer}from'./render/ThreeRenderer';import{Game}from'./core/Game';import{ViewManager}from'./render/ViewManager';import{ClassSystem}from'./systems/ClassSystem';import{CraftingSystem}from'./systems/CraftingSystem';import{STORY,QUEST_TITLE,objectiveFor,type DialogueLine}from'./content/story/ashenCryptIntro';
declare global{interface Window{__IGM_BOOTED__?:boolean}}const root=document.querySelector<HTMLDivElement>('#app');if(!root)throw Error('Missing #app root.');window.__IGM_BOOTED__=true;document.getElementById('boot-status')?.remove();
root.innerHTML=`<main class="shell"><section class="resource-strip"><span class="resource"><i>◉</i><b id="gold"></b><small>Gold</small></span><span class="resource"><i>◆</i><b id="gems"></b><small>Gems</small></span><span class="resource"><i>✦</i><b id="shards"></b><small>Shards</small></span></section><section id="game-canvas" class="game-canvas"></section><div id="location" class="location-card">GUILD TOWN</div><div id="quest" class="quest-card"></div><div id="joystick" class="joystick"><i></i></div><button id="interact" class="interact" hidden>INTERACT</button><button id="advance-zone" class="advance-zone-float" disabled hidden>NEXT ZONE →</button><section class="panel-stack"><article class="hud-card panel" data-view="heroes" hidden><h2>Hero & Job Hall</h2><div id="heroes-list" class="grid"></div></article><article class="hud-card panel" data-view="blacksmith" hidden><h2>Blacksmith</h2><button id="forge-demo">Forge Training Sword</button><pre id="forge-output"></pre></article><article class="hud-card panel" data-view="raid" hidden><h2>Ignis the Flame Sovereign</h2><button id="start-raid">Begin Raid</button><pre id="raid-status"></pre></article></section><div id="dialogue" class="dialogue" hidden><strong id="speaker"></strong><p id="line"></p><button id="continue">CONTINUE ›</button></div><div id="toast" class="toast" hidden></div><section class="save-tools"><button id="export-save">Export</button><button id="import-save">Import</button></section></main>`;
const host=document.querySelector<HTMLElement>('#game-canvas')!;const pixi=new PixiRenderer(),three=new ThreeRenderer(host),game=new Game(pixi,three);pixi.setEventBus(game.bus);await pixi.init(host,game.state,game.combat);new ViewManager(game.state,game.bus,root).mount();const crafting=new CraftingSystem();new ClassSystem();
let dialogue:DialogueLine[]=[];let di=0;let dialogueDone:(()=>void)|null=null;const joy=document.querySelector<HTMLElement>('#joystick')!,knob=joy.querySelector<HTMLElement>('i')!,interact=document.querySelector<HTMLButtonElement>('#interact')!,dialog=document.querySelector<HTMLElement>('#dialogue')!;let joyPointer:number|null=null;let input={x:0,y:0};
function toast(t:string){const e=document.querySelector<HTMLElement>('#toast')!;e.textContent=t;e.hidden=false;setTimeout(()=>e.hidden=true,1700)}function openDialogue(lines:DialogueLine[],done?:()=>void){dialogue=lines;di=0;dialogueDone=done||null;input={x:0,y:0};pixi.setTownInput(0,0);dialog.hidden=false;showLine()}function showLine(){const l=dialogue[di];document.querySelector('#speaker')!.textContent=l.speaker;document.querySelector('#line')!.textContent=l.text;}function nextLine(){if(++di<dialogue.length){showLine();return;}dialog.hidden=true;const d=dialogueDone;dialogueDone=null;d?.();}
document.querySelector('#continue')!.addEventListener('click',nextLine);
function interactNow(){if(!dialog.hidden){nextLine();return;}const t=pixi.townTarget;if(!t)return;const q=game.state.story.quest;if(t.id==='steward'){if(q==='NOT_STARTED')openDialogue(STORY.stewardIntro,()=>{game.state.setQuest('ACCEPTED');toast('QUEST ACCEPTED · '+QUEST_TITLE)});else if(q==='CRYPT_CLEARED'||q==='RETURNED_TO_GUILD')openDialogue(STORY.return,()=>{game.state.setQuest('COMPLETE');if(!game.state.story.rewardGranted){game.state.guild.gold+=150;game.state.guild.shards+=5;game.state.story.rewardGranted=true;game.state.save();}toast('QUEST COMPLETE · +150 GOLD · +5 SHARDS')});else openDialogue([{speaker:'Steward Elira',text:objectiveFor(q)}]);}
 else if(t.id==='party'){openDialogue(STORY.party,()=>{if(q==='ACCEPTED'||q==='INTRODUCED')game.state.setQuest('PARTY_MET')});}
 else if(t.id==='blacksmith'){openDialogue(STORY.blacksmith,()=>{if(q==='PARTY_MET')game.state.setQuest('PREPARED')});}
 else if(t.id==='board')openDialogue(STORY.board);
 else if(t.id==='crypt'){if(['NOT_STARTED','INTRODUCED','ACCEPTED','PARTY_MET'].includes(q))openDialogue(STORY.locked);else{if(q==='PREPARED')game.state.setQuest('ENTERED_CRYPT');(document.querySelector('.bottom-nav button:first-child') as HTMLButtonElement)?.click();toast('ASHEN CRYPT');}}}
interact.addEventListener('pointerdown',e=>{e.preventDefault();interactNow()});pixi.setTownTargetListener(t=>{interact.hidden=!t;interact.textContent=t?.label||'INTERACT'});
function joyMove(e:PointerEvent){if(e.pointerId!==joyPointer||!dialog.hidden)return;const r=joy.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),rad=r.width*.32,len=Math.hypot(dx,dy),s=Math.min(1,len/rad),dead=.12;if(s<dead)input={x:0,y:0};else input={x:dx/(len||1)*s,y:dy/(len||1)*s};knob.style.transform=`translate(${input.x*rad}px,${input.y*rad}px)`;pixi.setTownInput(input.x,input.y)}function joyEnd(e:PointerEvent){if(e.pointerId!==joyPointer)return;joyPointer=null;input={x:0,y:0};knob.style.transform='';pixi.setTownInput(0,0)}joy.addEventListener('pointerdown',e=>{joyPointer=e.pointerId;joy.setPointerCapture(e.pointerId);joyMove(e)});joy.addEventListener('pointermove',joyMove);joy.addEventListener('pointerup',joyEnd);joy.addEventListener('pointercancel',joyEnd);window.addEventListener('blur',()=>{input={x:0,y:0};pixi.setTownInput(0,0);knob.style.transform=''});
const keys=new Set<string>();addEventListener('keydown',e=>{keys.add(e.key.toLowerCase());if(e.key===' '||e.key.toLowerCase()==='e'){e.preventDefault();interactNow()}});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
const render=()=>{const{guild}=game.state;(document.querySelector('#gold')as HTMLElement).textContent=guild.gold.toLocaleString();(document.querySelector('#gems')as HTMLElement).textContent=guild.gems.toLocaleString();(document.querySelector('#shards')as HTMLElement).textContent=guild.shards.toLocaleString();document.querySelector('#quest')!.innerHTML=`<b>${QUEST_TITLE}</b><span>${objectiveFor(game.state.story.quest)}</span>`;document.querySelector('#heroes-list')!.innerHTML=game.state.heroes.slice(0,4).map(h=>`<div class="tile"><strong>${h.name}</strong><br>Lv.${h.level} · ${h.jobId}<br>HP ${h.currentHp}/${h.stats.maxHp}</div>`).join('');const n=document.querySelector<HTMLButtonElement>('#advance-zone')!;n.disabled=!game.combat.canAdvanceZone;n.hidden=!game.combat.canAdvanceZone;};
document.querySelector('#advance-zone')!.addEventListener('click',()=>{if(!game.combat.canAdvanceZone)return;if(game.state.story.quest==='ENTERED_CRYPT'||game.state.story.quest==='CRYPT_ATTEMPTED'){game.state.story.cryptObjectiveComplete=true;game.state.setQuest('CRYPT_CLEARED');toast('CRYPT INVESTIGATED · RETURN TO TOWN');}game.state.zoneLevel++;game.combat.resetEnemy(game.state.zoneLevel,true);game.state.save();render()});document.querySelector('#start-raid')?.addEventListener('click',()=>game.startRaid());document.querySelector('#forge-demo')?.addEventListener('click',()=>{game.state.guild.shards+=20;const item=crafting.forge(game.state.guild,'weapon',Math.max(1,game.state.zoneLevel),'rare');document.querySelector('#forge-output')!.textContent=JSON.stringify(item,null,2)});document.querySelector('#export-save')?.addEventListener('click',()=>window.prompt('Copy your save JSON:',game.state.exportJson()));document.querySelector('#import-save')?.addEventListener('click',()=>{const raw=window.prompt('Paste save JSON:');if(raw){game.state.importJson(raw);location.reload()}});
game.bus.on('save:complete',render);game.bus.on('loot:drop',render);game.bus.on('progress:zone-ready',render);game.bus.on('view:change',(e:any)=>{document.querySelector('#location')!.textContent=e.view==='town'?'GUILD TOWN':e.view==='dungeon'?'ASHEN CRYPT':'';if(e.view==='town'&&game.state.story.quest==='CRYPT_CLEARED')game.state.story.playerY=.72;render()});
let last=performance.now();function inputLoop(now:number){const dt=Math.min(.04,(now-last)/1000);last=now;if(root.dataset.view==='town'&&dialog.hidden&&joyPointer===null){let x=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),y=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0),l=Math.hypot(x,y)||1;pixi.setTownInput(x/l,y/l)}if(root.dataset.view==='town'&&Math.hypot(input.x,input.y)>0)pixi.setTownInput(input.x,input.y);requestAnimationFrame(inputLoop)}requestAnimationFrame(inputLoop);setInterval(()=>{if(root.dataset.view==='town')game.state.save()},5000);render();game.start();if(new URLSearchParams(location.search).get('storydebug')==='1')setInterval(()=>console.info('[story]',game.state.story,pixi.townTarget),3000);
